### ISSUE TITLE
Training on a custom dataset for point cloud merge registration, rather for aligning registration (non overlap area)

### ISSUE THREAD

**Issue by ttsesm** [prs-eth/OverlapPredator#40]
Hi guys,

Thank you for sharing your work, it is actually quite interesting. Would be easy to provide some hints whether it would be easy to use your pipeline to train on custom dataset?

My goal is a bit different from what you are doing in your work but at the same time quite similar. What I want to achieve is registering two point clouds so that they merge together rather than aligning. For example look on the two points clouds in the picture below:
![image](https://user-images.githubusercontent.com/10189018/153420282-7d6afd46-1d32-40a1-a553-b5761c30bb1c.png)
The two pcds connect at a specific part but they are two different instances of a bigger pcd.
If the two point clouds are randomly transformed:
![image](https://user-images.githubusercontent.com/10189018/153420343-ce190ae4-4dbe-4271-b60d-9e9fd0dacc9f.png)
I would like to get the transformation matrix which gives me the result in the first image.

I've tested the Teaser++ work and the fpfh feature descriptor vectors in order to extract meaningful correspondences:
![image](https://user-images.githubusercontent.com/10189018/153420441-c1945c4e-0a57-451b-9bfc-991c38f28d98.png)
but though the teaser+icp can correctly identify the side that the two pcds have the similarities (though this is not the case for all my dataset cases) it tries to align the two point clouds instead of stitching them together:
![image](https://user-images.githubusercontent.com/10189018/153420518-2846e122-f73a-4678-b4fe-e45c2d1c76df.png)
Thus, the extracted transformation is not correct since it tries to match similar points and not similar points in reverse. I was thinking whether I could use your pipeline for adjusting the correspondence points and how these match to each other, so that to force the alignment that I am seeking.

I also tried the pretrained indoor model, where I noticed the following:

On the current existing working example everything seems to work fine:
![image](https://user-images.githubusercontent.com/10189018/153424754-f29420dd-0c18-4d9a-b838-bee3ed581f2f.png)
However, once I add a bit of gaussian noise, it seems that is not able to generalize that good:
![image](https://user-images.githubusercontent.com/10189018/153425106-c4b3225a-267e-4887-acbc-d544999f1ca3.png)
and of course on the point clouds in my dataset doesn't work as well (quite expected though):
![image](https://user-images.githubusercontent.com/10189018/153425883-c9920dbc-74bb-43cb-bb8d-287182f4a815.png)

Thanks.

**Comment by ShengyuH** [comment]
Sorry I don't get your point. Have you solved the problem?

**Comment by ShengyuH** [comment]
Closed due to inactivity. Feel free to reopen if needed.
