### ISSUE TITLE
About download 3DLoMatch

### ISSUE THREAD

**Issue by WuHaoYu21** [prs-eth/OverlapPredator#44]
hi , i want to download 3DLoMatch dataset, but i don't know how to download and use it.
The 3DLoMatch and 3DMatch are the same dataset? or some differences?
I know these have different overlaps, but i want to use 3DLoMatch.
Does 3DLoMatch and 3DMatch have same train sets, and 3DLoMatch has another test sets?
Or i train a Model by 3DMatch, and test it by 3DLoMatch?

Looking forward to your reply, thank you!

**Comment by WuHaoYu21** [comment]
Thank you.
So, 3DLoMatch is part of 3DMatch.
If i want to use 3DLoMatch, i should threshold the overlap ratio and include pairs having 10-30% overlap ratios when i dataloader.
Sorry, i also have some questions.
In Predator, when test in 3DLoMatch , the train dataset is 3DMatch or 3DLoMatch?
And i don't know what is the 'benchmarks', a dataset or something else?
How to use the 'benchmarks'?
Sorry, my English is not good, would you mind using Chinese?
Or contact you by e-mail?

Looking forward to your reply, thank you very much!

**Comment by ShengyuH** [comment]
hi,

- The training split used in Predator includes pairs having 10-30% overlap ratios
- You can imagine benchmark as a competition, it includes the test dataset and evaluation metrics. Please refer to our evaluation part to see how we make use of the "benchmark". 

Best,
Shengyu

**Comment by WuHaoYu21** [comment]
Thank you,
Sorry, the training split includes (10~30% and >30%) or (10~30%), which one?
If i want to using 3DLoMatch,
first, i running 'sh scripts/download_data_weight.sh' to download 3DMatch preprocessed dataset,
second, i training model by download dataset(threshold (10~30% and >30%) or (10~30%)),
last, i evaluate this model by 'the benchmark'.
am i right?

Thank you very much!
Looking forward to your reply.

**Comment by ShengyuH** [comment]
the training split includes 10%-30% and >30%.

**Comment by WuHaoYu21** [comment]
Does your preprocessed 3DMatch dataset includes 10%-30% and >30%?
So when i training a model, i only need to using all training dataset (don't set the threshold, because the all training dataset includes 10%-30% and >30%).  
And if i want to test a model , i only using the 'benchmarks' to test it .
Does my understand is right?

**Comment by ShengyuH** [comment]
Yes. Feel free to reopen if needed.
