### ISSUE TITLE
About 3DLoMatch and benchmark

### ISSUE THREAD

**Issue by yi-C92** [prs-eth/OverlapPredator#45]
hi,
Thanks for your amazing work!
I want to use the 3DLoMatch dataset for testing recently. And I followed the steps in the README to change the benchmark in configs/test/indoor.yaml to 3DLoMatch, but I got an error，
“IndexError：index is out of bounds for axis 0 with size 1623”
I found that the error was in writing estimated trajectories of the seventh scence (sun3d-mit_76_studyrrom-76-1studyromm2). I'm not sure what I'm overlooking to get this error?
looking forward to your reply.

**Comment by ShengyuH** [comment]
Can you download the dataset again? I don't have such a problem.

**Comment by ShengyuH** [comment]
Closed due to inactivity. Feel free to reopen if needed.
