### ISSUE TITLE
When training ModelNet, there is an error, 'tensors used as indices must be long, byte or bool tensors'.

### ISSUE THREAD

**Issue by ChaunceyQ** [prs-eth/OverlapPredator#48]
After downloading the datasets and run 'python main.py configs/train/modelnet.yaml',  it always reminds that 'tensors used as indices must be long, byte or bool tensors'. I wonder what went wrong.

**Comment by ShengyuH** [comment]
please comment ```try ... except``` [here](https://github.com/prs-eth/OverlapPredator/blob/770c3063399f08b3836935212ab4c84d355b4704/lib/trainer.py#L188), then try to locate your bug. I didn't encounter this.

**Comment by Cindy-my** [comment]
Hey, when I run 'python main.py configs/train/indoor.yaml', I also had this problem. How did you solve the problem? Can you please share?
