### ISSUE TITLE
Regarding rotation and translation matrix in 3DMatch.pkl file

### ISSUE THREAD

**Issue by pomo1144** [prs-eth/OverlapPredator#49]
@ShengyuH 
Could you please let me know how you preprocessed the 3DMatch dataset to get the rotation and translation matrix for the pair of point clouds, that we use to evaluate and get the evaluation results? I am trying to evaluate on Redwood dataset where I have ground truth information but no rotation and translation matrix associated with each point cloud pair as we have in 3DMatch.pkl file.

Please help me out with this issue. That would be helpful for me to evaluate the predator model on the Redwood dataset as well.

**Comment by ShengyuH** [comment]
hi, 

I don't know about redwood dataset, but if each point cloud fragment is associated with one transformation matrix, then it's likely to be the global transformation matrix that aligns it to the global coordinate framework. Let's say we align two point cloud fragments X1 and X2 using T1 and T2 to global coordinate framework as T1X1 and T2X2, then their relative transformation matrix is: inv(T1)T2, that aligns X2 to X1, then inv(T1)T2[:3, :3] is the rotation matrix and inv(T1)T2[:3,3] the translation vector. 

Hope this helps.

**Comment by ShengyuH** [comment]
close due to in-activity.

**Comment by lcxiha** [comment]
> hi,
> 
> I don't know about redwood dataset, but if each point cloud fragment is associated with one transformation matrix, then it's likely to be the global transformation matrix that aligns it to the global coordinate framework. Let's say we align two point cloud fragments X1 and X2 using T1 and T2 to global coordinate framework as T1X1 and T2X2, then their relative transformation matrix is: inv(T1)T2, that aligns X2 to X1, then inv(T1)T2[:3, :3] is the rotation matrix and inv(T1)T2[:3,3] the translation vector.
> 
> Hope this helps.

Hi,I want to consult whether the rotation matrix and the translation matrix obtained by preprocessing the data set are based on the global coordinate system or the carrier coordinate system (sensor coordinate system)?Please help me.Thanks a lot!

**Comment by lcxiha** [comment]
> @ShengyuH Could you please let me know how you preprocessed the 3DMatch dataset to get the rotation and translation matrix for the pair of point clouds, that we use to evaluate and get the evaluation results? I am trying to evaluate on Redwood dataset where I have ground truth information but no rotation and translation matrix associated with each point cloud pair as we have in 3DMatch.pkl file.
> 
> Please help me out with this issue. That would be helpful for me to evaluate the predator model on the Redwood dataset as well.

Hello, if using my own dataset, do you know how to build point cloud data pth files?
