### ISSUE TITLE
How we can predict rigid transformation between pair of point clouds?

### ISSUE THREAD

**Issue by pomo1144** [prs-eth/OverlapPredator#50]
@ShengyuH 
For evaluation, our registration algorithm i.e. PREDATOR here should determine whether the pair of the point clouds can be aligned and if so, the model should output the predicted rigid transformation to a log file. This log file then we can use for evaluation purposes.
So could you please help me out here and guide me on how we can predict the rigid transformation between pair of point clouds files using the PREDATOR model and use the same for evaluation purposes as mentioned out here http://3dmatch.cs.princeton.edu/#geometric-registration-benchmark  

Thanks in Advance :)

**Comment by ShengyuH** [comment]
Can you go through the demo we provide first? The evaluation is implemented in ```benchmark.py```

**Comment by ShengyuH** [comment]
Close due to inactivity.
