### ISSUE TITLE
About preprocessing the 3DMatch dataset.

### ISSUE THREAD

**Issue by rust-in** [prs-eth/OverlapPredator#51]
First, thank you for this solid work!

As we want to further explore this work, I wonder if you would like to share the preprocess script on 3DMatch dataset for transforming the raw 3DMatch dataset to the training data?

Also, I notice that the raw 3DMatch dataset you provide is different from the official 3DMatch dataset, can you please illustrate the difference between these two?

Thank you and look forward to your reply!

**Comment by ShengyuH** [comment]
Close as this is a repetition, see https://github.com/prs-eth/OverlapPredator/issues/58#issue-1444886610

**Comment by lcxiha** [comment]
Hi.Do you now know how to obtain the preprocessed dataset? Could you please help me answer? I would greatly appreciate it.

**Comment by lcxiha** [comment]
> First, thank you for this solid work!
> 
> As we want to further explore this work, I wonder if you would like to share the preprocess script on 3DMatch dataset for transforming the raw 3DMatch dataset to the training data?
> 
> Also, I notice that the raw 3DMatch dataset you provide is different from the official 3DMatch dataset, can you please illustrate the difference between these two?
> 
> Thank you and look forward to your reply!

Hi.Do you now know how to obtain the preprocessed dataset? Could you please help me answer? I would greatly appreciate it.
