### ISSUE TITLE
Unable to download 3DMatch data

### ISSUE THREAD

**Issue by chienerh** [prs-eth/OverlapPredator#55]
Hi authors, 
Thank you for the amazing work!

I followed README to download 3DMatch data. I tried downloading preprocessed data with `sh scripts/download_data_weight.sh` and raw dense data with `wget --no-check-certificate --show-progress https://share.phys.ethz.ch/~gsg/pairwise_reg/3dmatch.zip`. They all have 403 Forbidden error. I wonder if the download link is changed? 

Thank you for your help!

```
wget --no-check-certificate --show-progress https://share.phys.ethz.ch/~gsg/Predator/data.zip
--2022-09-26 23:56:13--  https://share.phys.ethz.ch/~gsg/Predator/data.zip
Resolving share.phys.ethz.ch (share.phys.ethz.ch)... 129.132.80.27, 2001:67c:10ec:3dc4::39
Connecting to share.phys.ethz.ch (share.phys.ethz.ch)|129.132.80.27|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2022-09-26 23:56:13 ERROR 403: Forbidden.
```

**Comment by yaoyhAmit** [comment]
I have the same error

**Comment by ShengyuH** [comment]
It was an issue with our server, now it should work. Sorry for the interruption.

**Comment by chienerh** [comment]
Thank you for fixing it in a short time!

**Comment by fog223** [comment]
Hello, I have encountered the same problem. I have tried to download the preprocessed data and models multiple times using the command "sh scripts/download_data_weight.sh", but I keep getting a 403 Forbidden error. Is there any other way to download them? Thank you.

**Comment by soosoonet** [comment]
Hi there, 
I'm currently exploring the model and I've encountered an issue: the links to download the data and weights files seem to be unavailable. If you happen to have these files, could you please share them with me at changbumlee1415@gmail.com? I'd greatly appreciate your assistance. Thank you so much!!

**Comment by ShengyuH** [comment]
Can you pull the latest change and check again ? 

```
wget --no-check-certificate --show-progress https://share.phys.ethz.ch/~gseg/Predator/data.zip
wget --no-check-certificate --show-progress https://share.phys.ethz.ch/~gseg/Predator/weights.zip
unzip data.zip
unzip weights.zip
rm data.zip
rm weights.zip
```
