### ISSUE TITLE
Unable to download 3DMatch data！

### ISSUE THREAD

**Issue by QiuJunning** [prs-eth/OverlapPredator#56]
Hi, thanks for sharing！But I got an error "404 Not Found" while downloading the dataset by "sh scripts/download_data_weight.sh".

**Comment by rhyme111** [comment]
> Hi, thanks for sharing！But I got an error "404 Not Found" while downloading the dataset by "sh scripts/download_data_weight.sh".

May I ask if you have solved this issue? Do you still have these data?
