### ISSUE TITLE
About the preprocessing scripts

### ISSUE THREAD

**Issue by Hui-design** [prs-eth/OverlapPredator#58]
First, thank you for this solid work!

As we want to further explore this work, I wonder if you would like to share the preprocess script on 3DMatch dataset for transforming the raw 3DMatch dataset to the training data?

Also, I notice that the raw 3DMatch dataset you provide is different from the official 3DMatch dataset, can you please illustrate the difference between these two?

Thank you and look forward to your reply!

**Comment by ShengyuH** [comment]
hi @zgojcic, do you have any pointers for that?

**Comment by lcxiha** [comment]
> First, thank you for this solid work!
> 
> As we want to further explore this work, I wonder if you would like to share the preprocess script on 3DMatch dataset for transforming the raw 3DMatch dataset to the training data?
> 
> Also, I notice that the raw 3DMatch dataset you provide is different from the official 3DMatch dataset, can you please illustrate the difference between these two?
> 
> Thank you and look forward to your reply!

Hi.Do you now know how to obtain the preprocessed dataset? Could you please help me answer? I would greatly appreciate it.

**Comment by ShengyuH** [comment]
Just download our preprocessed ones.

**Comment by lcxiha** [comment]
But I want to apply this algorithm to my dataset, so I want to know how the preprocessed dataset was obtained. Can you please help me ?
