### ISSUE TITLE
download Dataset issue:403 forbidden

### ISSUE THREAD

**Issue by 940235carl** [prs-eth/OverlapPredator#59]
Hello, when I am currently experimenting with your program, I have encountered a problem that the data cannot be downloaded, and a 403 forbidden error has jumped out. Is there any other way to download your dataset? Thanks

**Comment by ShengyuH** [comment]
hi, I just tried out and it worked for me. Can you try again?

**Comment by 940235carl** [comment]
It works!! Thank you. I will close the issue
