### ISSUE TITLE
Download the pre-computed descriptors for the 3DLoMatch

### ISSUE THREAD

**Issue by Xinyi-tum** [prs-eth/OverlapPredator#60]
Hello! Thanks for your open source code and data!

Do you know where is the link that I can download the pre-computed descriptors (Predator and FCGF) for the 3DLoMatch?

I'm looking forward to your reply.

**Comment by ShengyuH** [comment]
hi, sorry we don't provide it, you can run the inference on your own.

**Comment by hiyyg** [comment]
Hi @ShengyuH could you share the datasets and weights again? The links are broken now.
