### ISSUE TITLE
Demo .py [Alignment ouptuts identity transfortmation matrix]

### ISSUE THREAD

**Issue by somdats** [prs-eth/OverlapPredator#63]
@ShengyuH @zgojcic 
I am running the demo script of your source code. I managed to execute the script without any compile/run error, but the output transformation is identity, i,e, it does not align.
I have not made any changes in the config file as provided to run the demo
Are there any modifications that I need to make in the config file? 
Here is a snapshot of the visualizer.
![image](https://user-images.githubusercontent.com/4468850/222492987-a8f6831a-9c21-4e05-bbb2-9af51da16f1a.png)

**Comment by ShengyuH** [comment]
Close as it's a duplicate, see: https://github.com/prs-eth/OverlapPredator/issues/61
