### ISSUE TITLE
Coordinate system of data

### ISSUE THREAD

**Issue by lcxiha** [prs-eth/OverlapPredator#68]
Hi，May I ask if the dataset used in the paper is in the global coordinate system or in the carrier coordinate system.Looking forward to your reply.

**Comment by ShengyuH** [comment]
It doesn't matter.

**Comment by lcxiha** [comment]
Because I want to use this algorithm in point cloud map matching in SLAM, I want to know which coordinate system is used to get the rotation matrix and translation matrix.Looking forward to your reply.
