### ISSUE TITLE
Cannot download dataset or model weights

### ISSUE THREAD

**Issue by shahyaan** [prs-eth/OverlapPredator#78]
Hi,

Running the script to download the dataset and model results in the following:
--2023-11-17 16:27:08--  https://share.phys.ethz.ch/~gsg/Predator/weights.zip
Resolving share.phys.ethz.ch (share.phys.ethz.ch)... 129.132.80.27
Connecting to share.phys.ethz.ch (share.phys.ethz.ch)|129.132.80.27|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-11-17 16:27:12 ERROR 403: Forbidden.

unzip:  cannot find or open data.zip, data.zip.zip or data.zip.ZIP.
unzip:  cannot find or open weights.zip, weights.zip.zip or weights.zip.ZIP.
rm: cannot remove 'data.zip': No such file or directory
rm: cannot remove 'weights.zip': No such file or directory

It seems that there is an issue with your servers again. Is it possible to get the training data and model weights another way or fix the link?

Thanks in advance, and for some really great work!

**Comment by shahyaan** [comment]
Server link works again...thank you!

**Comment by hiyyg** [comment]
Hi @shahyaan Could you share the data and weights? The provided links do not work.

**Comment by jun3333333** [comment]
Hi there,
I'm currently exploring the model and I've encountered an issue: the links to download the data and weights files seem to be unavailable. If you happen to have these files, could you please share them with me at 2373178085@qq.com? I'd greatly appreciate your assistance. Thank you so much!!

**Comment by doge0216** [comment]
Hello, I have also encountered this issue, the current download link is returning a 404 error.
I would greatly appreciate it if you could send me the 3dmatch.zip file. My email address is [[2015352829@qq.com](mailto:2015352829@qq.com)]. Thank you very much for your assistance.
