### ISSUE TITLE
RT is a prerequisite for the model

### ISSUE THREAD

**Issue by zero-joke** [prs-eth/OverlapPredator#82]
I want to use the model to predict the RT matrix between two point clouds, but a prerequisite RT matrix is needed as the input of model. How can I avoid this input.

**Comment by heyyviv** [comment]
how did you fixed torch-1.7.1-cp38-cp38-win_amd64.whl is not at all compatiable with torchvision==0.8.2

**Comment by ShengyuH** [comment]
hi, if the GT is not available, you can simply set them to be identity metrix in your data loader. Our model can predict it for you.

**Comment by jun3333333** [comment]
您好，我用自己的源云和目标云文件运行 demo.py 进行注册，效果不是很好，请问如何提高我的注册效果，请发到我的邮箱：2373178085@qq.com
